name: 'Resolve Merge Conflicts'
description: 'Resolves merge conflicts in shared/build.gradle.kts'
inputs:
  branch:
    description: 'The branch to merge'
    required: true
  ui:
    description: 'The UI framework'
    required: true
runs:
  using: "composite"
  steps:
    - name: Determine branch
      shell: bash
      run: |
        if [[ "${{ inputs.ui }}" == "compose_swift_ui" ]]; then
          BRANCH="${{ inputs.branch }}_swift_ui"
        else
          BRANCH="${{ inputs.branch }}"
        fi
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    - name: Merge branch
      shell: bash
      run: |
        echo $BRANCH
        git merge origin/$BRANCH || {
          if [[ "${{ inputs.ui }}" == "compose_swift_ui" ]]; then git checkout --ours shared/build.gradle.kts; else git checkout --ours composeApp/build.gradle.kts; fi
          scripts/fix_conflicts.sh
          git add .
          git commit -m "Fixed merge conflicts"
          scripts/add_dependencies.sh origin/${{ inputs.ui }} origin/$BRANCH
          scripts/remove_duplications_in_toml_file.sh
          if [[ "${{ inputs.ui }}" == "compose_swift_ui" ]]; then git add shared/build.gradle.kts; else git add composeApp/build.gradle.kts; fi
          git commit -m "Fixed merge conflicts"
        }
